services:
  # service_bot:
  #   build: service_bot/
  db:
    image: postgres:15
    container_name: service_bot_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
    restart: always

volumes:
  postgres_data:
networks:
  backend:
    driver: bridge 
